### ISSUE TITLE
Remote debugging not working

### ISSUE THREAD

**Issue by ramyodev** [telerik/fiddler-everywhere#21]
**Describe the bug**
Fiddler CA Download not possible to use Remote Devices.

 - Used Operating System: macOS Sonoma 14.4
 - Affected Fiddler UI: Remote Devices prompt
 - Affected functionality (HTTPS capturing, gRPC, Browser capturing, WebSockets, etc.): Everything mobile

**To Reproduce**
1. Go to Home
2. Click on Remote Devices -> Click next -> Nothing on Dropdown
3. See no options in list

**Expected behavior**
See Web Address to download CA.

**Additional context**
Just downloaded, got the license but cant see web address to connect to, to get the CA. Neither IOS nor anything else works to download the CA.

<img width="948" alt="image" src="https://github.com/telerik/fiddler-everywhere/assets/60301473/611d12c3-2682-4602-a629-9ad7be105b78">

Also this shows no server:

<img width="1030" alt="image" src="https://github.com/telerik/fiddler-everywhere/assets/60301473/1b7f8dc3-cb2a-4cb9-92c3-9920102b5f6e">

**Comment by ramy-zemo** [comment]
<img width="1030" alt="image" src="https://github.com/telerik/fiddler-everywhere/assets/60301473/f2908510-0146-4cc6-bec6-b59d00833dd7">
Also this shows no server

**Comment by NickIliev** [comment]
@ramy-zemo, you can send us[ the Fiddler Everywhere application log files](https://docs.telerik.com/fiddler-everywhere/knowledge-base/accessing-fiddler-logs) (it's probably best to do it through the internal support channel at [Telerik's Support Center](https://www.telerik.com/account/support-center), as they might contain personal information) so that we can investigate further what causes the drop-down not to be properly populated.

That said, if the Fiddler Everywhere application is working as expected on the host machine, and both devices are on the same network (and that network is not limited by a third-party tool or policy), then you should be able to access the host machine through the steps described in the manual configuration (where the server address is the IP of the Fiddler host):
https://docs.telerik.com/fiddler-everywhere/capture-traffic/capture-from-ios#configuring-the-fiddler-proxy-on-ios-device
