### ISSUE TITLE
adding rule to find and replace its not decode

### ISSUE THREAD

**Issue by mohavved** [telerik/fiddler-everywhere#33]
hello 
when I add rule and choose action to find and replace in update body of response its not decode to find and replace correctly 
work solution add break point then change the response manually then resume everytime
please fix it ASAP

**Comment by NickIliev** [comment]
@mohavved 

Ensure that you have turned off the streaming mode
![image](https://github.com/user-attachments/assets/ab8443ff-21a9-4293-a745-c8f0f3ad3792)

Additionally, check if you have a final rule/action before executing the rule that modifies the response. Learn more about final and non-final actions from the following documentation section:
https://docs.telerik.com/fiddler-everywhere/modify-and-filter-traffic/conditions-and-actions#final-and-non-final-actions 

For your convenience, I've made a sample FARX file that contains a rule that replaces the "Fiddler Everywhere" string with the "Fiddler Everywhere RULLZ" string. The FARX file is included in this ticket as a ZIP archive.

The targeted endpoint (in the attached rule) is as follows:

https://docs.telerik.com/fiddler-everywhere/introduction  

Could you try to reproduce the issue with the above endpoint (or any other endpoint you can share) by creating a rule to show the issue? Then, please send us the generated rule so that we can investigate further.
[5c5e9f7e-2cae-4a67-803e-1f749aa6cfdb_fiddler-everywhere-farx.zip](https://github.com/user-attachments/files/16687815/5c5e9f7e-2cae-4a67-803e-1f749aa6cfdb_fiddler-everywhere-farx.zip)
