### ISSUE TITLE
Sign In Failure

### ISSUE THREAD

**Issue by saduncan084** [telerik/fiddler-everywhere#36]
When attempting to sign in i get the attached failure 
![Screenshot 2024-08-25 at 3 27 36 AM](https://github.com/user-attachments/assets/8a19e75e-da83-4323-8420-dee9f724baf9)

**Comment by NickIliev** [comment]
Hey @saduncan084 

As suggested in the error messages, you need access to the required endpoints. This could be because of restrictions applied through administrative policies or security tools installed by your network administrators. The best approach is to contact your network administrators and ask them to allow the Fiddler Everywhere application and its required endpoints so that you can successfully authenticate and use the tool.

You can also use the following KB article for a list of other possibilities preventing Fiddler Everywhere from properly starting up. 

https://docs.telerik.com/fiddler-everywhere/knowledge-base/troubleshoot-fiddler-not-capturing
