### ISSUE TITLE
Failed to Enable HTTPS

### ISSUE THREAD

**Issue by gibbsr** [telerik/fiddler-everywhere#44]
Clicking Trust and enable HTTPS fails with Fiddler Root Certificate was NOT trusted successfully.

**To Reproduce**
[Enable HTTPS now.pdf](https://github.com/user-attachments/files/17523796/Enable.HTTPS.now.pdf)

Displays:
[Enable Trust popup.pdf](https://github.com/user-attachments/files/17523835/Enable.Trust.popup.pdf)

Click Enable Https button:

[Certificate Trust Error.pdf](https://github.com/user-attachments/files/17523838/Certificate.Trust.Error.pdf)

No other popups display.

Per the message in the popup above, I should get another system popup nothing appears.

I did try it with a normal user, as well as running the app with admin privilege's, but the behavior is the same with both.

Please Advise.

**Comment by NickIliev** [comment]
The error message suggests that something is preventing your operating system from automatically installing the Fiddler certificate authority file. Several factors could be causing this issue, including administrative policies and security tools (like antivirus software, firewalls, or zero-trust tools).

To gather more information about the issue, you can check the application log files for Fiddler Everywhere. You can access these logs by navigating to **Help > Open Application Logs Folder**. If necessary, consult your network or system administrators for assistance in [manually adding the Fiddler Everywhere CA to your system](https://docs.telerik.com/fiddler-everywhere/installation-and-setup/trust-fiddler-ca#install-the-fiddlers-certificate-authority-manual-approach).

If there are no third-party tools or policies blocking the installation of the Fiddler CA, and you think the issue is solely related to the automated setup in Fiddler, please send us the application logs in a private thread through[ Telerik's Support Center](https://www.telerik.com/account/support-center).
