### ISSUE TITLE
I can't activate the Fiddler Everywhere account

### ISSUE THREAD

**Issue by salarico** [telerik/fiddler-everywhere#45]
I'm installing Fiddler Everywhere and when I'm at the point where I get an email with the link to activate my account, every time I click or copy the link I get an error message saying Your Activation Link is Invalid, I'm including the screen shot of the email and the message I got. I click the link the minute I got the email.
<img width="567" alt="Screenshot 2024-11-05 121438" src="https://github.com/user-attachments/assets/868dab02-8de0-4d57-90c5-75db1e47bf53">
<img width="589" alt="Screenshot 2024-11-05 121228" src="https://github.com/user-attachments/assets/0294ef50-aeba-48af-ba44-385a449fe88f">

**Comment by NickIliev** [comment]
Hey @salarico 

The issue is related to the account you use within Telerik.com. If opening a private ticket through [the Support Center](https://www.telerik.com/account/support-center) is not possible, then please share with us the email address you use (and which fails to receive the activation links) so that we can investigate further
