### ISSUE TITLE
Something Went Wrong

### ISSUE THREAD

**Issue by bhabgs** [telerik/fiddler-everywhere#49]
Operating System: macOS 14.4.1
User Principal Email: 
Has Jamf Connect installed: False

**Comment by endarova** [comment]
Hi bhabgs,

In order to login in Fiddler Everywhere you need to have an active Internet connection with access to the following URLs:

```
- https://*.telerik.com/
- https://*.getfiddler.com/
- https://fiddler-backend-production.s3-accelerate.amazonaws.com 
- https://challenges.cloudflare.com 
```

In your environment you may have restrictions applied through administrative policies or security tools installed by your network administrators. The best approach is to contact your network administrators and ask them to allow the Fiddler Everywhere application and its required endpoints so that you can successfully authenticate and use the tool. If you have checked the connectivity to the described URLs and you still have problems logging in we will need more information in order to assist you further. You can send us the Fiddler Everywhere application logs and information about your environment setup in a private thread through [Telerik's Support Center](https://www.telerik.com/account/support-center)
